name = "deutschlern-app"
compatibility_date = "2024-01-01"

# Configuration for Cloudflare Pages
[build]
command = ""
publish = "."

# Define which files to include
[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.js", "**/*.json"]
fallthrough = false